id: P585E9C48
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4522
  instance_id: http://purl.bdrc.io/resource/IE1KG4522
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - ཚད་མའི་རིགས་ལམ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P9569
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    d4b66a6bbdec44e6a0edad6118d54726:
      title: པོད ༡་ཚད་མའི་རིགས་ལམ
      volume_number: 1
      base_file: UT1KG4522_I1KG4541_0000.txt
      reference: http://purl.bdrc.io/resource/VL367BC0B8A3A9DC6A
      image_group: I1KG4541
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4522
  - http://purl.bdrc.io/resource/W1KG4522
  ocr_software: Namsel
created_at: '2021-12-22T10:42:10.088666'
last_modified_at: '2021-12-22T10:42:10.088673'
statistics:
  total_words: 55651
  total_non_words: 10856
quality:
  non_words_ratio: 0.2
